server.port=8082
spring.application.name=prescription-service

# Logging Configuration
logging.level.root=INFO
logging.level.com.prescription.demo=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.ws=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %-5level [%thread] %logger{36} - %msg%n

# Validation Service URL (can be overridden by environment variable)
validation.service.url=http://validation-service:8081/api/validate

# Pharmacy Service URL (can be overridden by environment variable)
pharmacy.service.url=http://pharmacie-service:8080/ws